# Generated by Django 3.1.7 on 2021-04-14 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise',
            field=models.TextField(max_length=30),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.TextField(max_length=30)),
                ('duration', models.IntegerField()),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('challengedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengedBy', to=settings.AUTH_USER_MODEL)),
                ('personChallenged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personChallenged', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
