# Generated by Django 3.1.7 on 2021-04-22 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0002_auto_20210414_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.TextField(max_length=30)),
                ('duration', models.IntegerField()),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('done', models.BooleanField(verbose_name=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
