# Generated by Django 3.1.7 on 2021-04-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_employerchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerchallenge',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
