# Generated by Django 3.1.7 on 2021-04-23 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0005_employerchallenge_carrot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerchallenge',
            name='done',
        ),
        migrations.RemoveField(
            model_name='employerchallenge',
            name='employee',
        ),
        migrations.AddField(
            model_name='employerchallenge',
            name='completers',
            field=models.ManyToManyField(related_name='completers', to=settings.AUTH_USER_MODEL),
        ),
    ]
