# Generated by Django 3.1.7 on 2021-04-23 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0006_auto_20210423_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employerchallenge',
            name='completers',
            field=models.ManyToManyField(related_name='completers', to='exercises.Completer'),
        ),
    ]
